"""Adiciona campo de versao ao checklist

Revision ID: 1098affea807
Revises: ea372ca3f314
Create Date: 2025-09-09 14:26:44.507293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1098affea807'
down_revision = 'ea372ca3f314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('versao', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('versao')

    # ### end Alembic commands ###
