"""Implementa arquitetura de modelos de checklist

Revision ID: bb2299c793b0
Revises: 
Create Date: 2025-09-12 16:32:21.932000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2299c793b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('perfil', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_matricula'), ['matricula'], unique=True)

    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('setor', sa.String(length=120), nullable=True),
    sa.Column('tipo_ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_ativo_id'], ['tipo_ativo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativo_codigo'), ['codigo'], unique=True)

    op.create_table('item_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.String(length=300), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo_tipo_ativo',
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_checklist.id'], ),
    sa.ForeignKeyConstraint(['tipo_ativo_id'], ['tipo_ativo.id'], ),
    sa.PrimaryKeyConstraint('modelo_id', 'tipo_ativo_id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_checklist.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_timestamp'), ['timestamp'], unique=False)

    op.create_table('checklist_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=300), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['item_modelo_id'], ['item_modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_resposta')
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_timestamp'))

    op.drop_table('checklist')
    op.drop_table('modelo_tipo_ativo')
    op.drop_table('item_modelo')
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativo_codigo'))

    op.drop_table('ativo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_matricula'))

    op.drop_table('usuario')
    op.drop_table('tipo_ativo')
    op.drop_table('modelo_checklist')
    # ### end Alembic commands ###
