"""Tabelas iniciais de usuarios e ativos

Revision ID: d35c4d076c8a
Revises: 
Create Date: 2025-09-09 14:08:17.738891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35c4d076c8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('setor', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativo_codigo'), ['codigo'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('perfil', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_matricula'), ['matricula'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_matricula'))

    op.drop_table('usuario')
    with op.batch_alter_table('ativo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativo_codigo'))

    op.drop_table('ativo')
    # ### end Alembic commands ###
