"""Adiciona tabelas de checklist

Revision ID: ea372ca3f314
Revises: d35c4d076c8a
Create Date: 2025-09-09 14:12:15.163783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea372ca3f314'
down_revision = 'd35c4d076c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('validado_por_lider', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ativo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_timestamp'), ['timestamp'], unique=False)

    op.create_table('checklist_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=300), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('item_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.ForeignKeyConstraint(['item_template_id'], ['item_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_resposta')
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_timestamp'))

    op.drop_table('checklist')
    op.drop_table('item_template')
    # ### end Alembic commands ###
