"""Add training fields and two signatures

Revision ID: 5a329ba924fa
Revises: b934d49ed4e3
Create Date: 2025-07-28 10:45:04.003085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a329ba924fa'
down_revision = 'b934d49ed4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assinatura')
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treinador', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('carga_horaria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processo_treinamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_funcionario_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('nome_funcionario_assinatura', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_hora_funcionario_assinatura', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assinatura_gestor_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('nome_gestor_assinatura', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_hora_gestor_assinatura', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_column('data_hora_gestor_assinatura')
        batch_op.drop_column('nome_gestor_assinatura')
        batch_op.drop_column('assinatura_gestor_data')
        batch_op.drop_column('data_hora_funcionario_assinatura')
        batch_op.drop_column('nome_funcionario_assinatura')
        batch_op.drop_column('assinatura_funcionario_data')
        batch_op.drop_column('processo_treinamento')
        batch_op.drop_column('carga_horaria')
        batch_op.drop_column('treinador')

    op.create_table('assinatura',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('checklist_id', sa.INTEGER(), nullable=False),
    sa.Column('assinatura_data', sa.BLOB(), nullable=False),
    sa.Column('data_hora_assinatura', sa.DATETIME(), nullable=False),
    sa.Column('nome_assinante', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tipo_assinatura', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
