"""Initial migration

Revision ID: b934d49ed4e3
Revises: 
Create Date: 2025-07-28 10:28:51.845214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b934d49ed4e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_checklist', sa.String(length=100), nullable=False),
    sa.Column('itens_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('data_preenchimento', sa.Date(), nullable=False),
    sa.Column('avaliador', sa.String(length=100), nullable=False),
    sa.Column('setor', sa.String(length=100), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('assinatura_data', sa.LargeBinary(), nullable=False),
    sa.Column('data_hora_assinatura', sa.DateTime(), nullable=False),
    sa.Column('nome_assinante', sa.String(length=100), nullable=True),
    sa.Column('tipo_assinatura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('item_nome', sa.String(length=200), nullable=False),
    sa.Column('valor_preenchido', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_item')
    op.drop_table('assinatura')
    op.drop_table('checklist')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
