"""Adiciona pontuacao e situacao ao modelo de respostas

Revision ID: 1b8cfafacc96
Revises: 44a2c415d774
Create Date: 2025-08-11 12:21:57.555298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8cfafacc96'
down_revision = '44a2c415d774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respostas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pontuacao_final', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('situacao', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_respostas', schema=None) as batch_op:
        batch_op.drop_column('situacao')
        batch_op.drop_column('pontuacao_final')
        batch_op.drop_column('respostas')

    # ### end Alembic commands ###
