"""Criação das tabelas iniciais

Revision ID: 44a2c415d774
Revises: 
Create Date: 2025-08-11 12:01:04.473382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a2c415d774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('itens', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lider_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['setor_id'], ['setor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliador_colaborador',
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['avaliador_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.PrimaryKeyConstraint('avaliador_id', 'colaborador_id')
    )
    op.create_table('checklist_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_preenchimento', sa.DateTime(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('assinaturas', sa.JSON(), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['checklist_modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_respostas')
    op.drop_table('avaliador_colaborador')
    op.drop_table('colaborador')
    op.drop_table('usuario')
    op.drop_table('setor')
    op.drop_table('checklist_modelo')
    # ### end Alembic commands ###
