"""Initial complete database schema for training system

Revision ID: 4c45476a1346
Revises: 
Create Date: 2025-08-08 20:37:01.193654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c45476a1346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('checklist_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_item_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('is_score_item', sa.Boolean(), nullable=True),
    sa.Column('score_block', sa.String(length=50), nullable=True),
    sa.Column('requires_comment_if_not_ok', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name='fk_item_template'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], name='fk_employee_sector'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('checklist_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_number', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('fill_date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('signature_leader_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_evaluator_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_employee_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='fk_instance_employee'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['user.id'], name='fk_instance_evaluator'),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name='fk_instance_leader'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name='fk_instance_template'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_number')
    )
    op.create_table('checklist_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['checklist_instance.id'], name='fk_answer_instance'),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_item_template.id'], name='fk_answer_item'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_answer')
    op.drop_table('checklist_instance')
    op.drop_table('user')
    op.drop_table('employee')
    op.drop_table('checklist_item_template')
    op.drop_table('sector')
    op.drop_table('role')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
