"""Versao final com JSON padrao

Revision ID: 6ac6ef333389
Revises: 
Create Date: 2025-09-19 19:13:44.949655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac6ef333389'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('sector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['setor_id'], ['sector.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('cargo', sa.Enum('COLABORADOR', 'GESTOR', 'COORDENADOR', name='userroles'), nullable=False),
    sa.Column('setor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setor_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('assinatura_colaborador', sa.Text(), nullable=False),
    sa.Column('assinatura_gestor', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_data'), ['data'], unique=False)

    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('enviado_para', sa.String(length=255), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    with op.batch_alter_table('checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_data'))

    op.drop_table('checklist')
    op.drop_table('user')
    op.drop_table('question')
    op.drop_table('equipment')
    op.drop_table('sector')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
