"""Initial complete database schema

Revision ID: 9fab04b7a400
Revises: 
Create Date: 2025-07-30 19:50:34.896909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fab04b7a400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_item_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('requires_comment_if_no', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name='fk_checklist_item_template_template'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_user_id', sa.Integer(), nullable=True),
    sa.Column('evaluated_employee_name', sa.String(length=100), nullable=False),
    sa.Column('employee_matricula', sa.String(length=50), nullable=True),
    sa.Column('employee_position', sa.String(length=100), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('training_coach', sa.String(length=100), nullable=False),
    sa.Column('training_load_hours', sa.String(length=50), nullable=True),
    sa.Column('training_process_desc', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('saved_partially', sa.Boolean(), nullable=True),
    sa.Column('evaluator_signature_data', sa.LargeBinary(), nullable=True),
    sa.Column('evaluator_signature_name', sa.String(length=100), nullable=True),
    sa.Column('evaluator_signature_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], name='fk_checklist_creator'),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['user.id'], name='fk_checklist_evaluator'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_template.id'], name='fk_checklist_template'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('item_template_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name='fk_checklist_answer_checklist'),
    sa.ForeignKeyConstraint(['item_template_id'], ['checklist_item_template.id'], name='fk_checklist_answer_item_template'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('validator_user_id', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('validation_datetime', sa.DateTime(), nullable=True),
    sa.Column('signature_data', sa.LargeBinary(), nullable=True),
    sa.Column('signature_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], name='fk_validation_log_checklist'),
    sa.ForeignKeyConstraint(['validator_user_id'], ['user.id'], name='fk_validation_log_validator'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_log')
    op.drop_table('checklist_answer')
    op.drop_table('checklist')
    op.drop_table('user')
    op.drop_table('checklist_item_template')
    op.drop_table('role')
    op.drop_table('checklist_template')
    # ### end Alembic commands ###
